/** Generated by scripts/write-production-env.mjs — do not edit. */
export const productionGeneratedConfig = {
  supabaseUrl: 'https://x.supabase.co',
  supabaseAnonKey: 'test',
  importCronSecret: 'test',
} as const;
