#!/usr/bin/env sh
staged_files=$(git diff --cached --name-only --diff-filter=ACMR)
if [ -z "$staged_files" ]; then
  exit 0
fi

echo "$staged_files" | xargs pnpm exec prettier --write --ignore-unknown
echo "$staged_files" | xargs git add
